apiVersion: v1
kind: Service
metadata:
  name: todo-app-api
  labels:
    app: todo-app-api
    component: todo-app-api
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: todo-app-api
