apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  #TODO: GCP ingress
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: todo-app-ui
            port:
              number: 8080
