apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-ui
  labels:
    app: todo-app-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-app-ui
  template:
    metadata:
      labels:
        app: todo-app-ui
    spec:
      containers:
      - name: todo-app-ui
        image: todo-app-ui:1.0.0
        ports:
        - containerPort: 8080
