apiVersion: v1
kind: Service
metadata:
  name: todo-app-ui
  labels:
    app: todo-app-ui
    component: todo-app-ui
spec:
  type: ClusterIP #TODO: Change to LoadBalancer?
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 443
  selector:
    app: todo-app-ui